package test;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.apache.solr.client.solrj.SolrServerException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alexandre
 */
public class IPadsearch extends javax.swing.JFrame {
    solrj j;
    boolean isFirstTime = true;
    IPadresults resultPanel = new IPadresults();
    JPanel panel;
    String[] queryList = new String[9];
    /**
     * Creates new form IPadsearch
     */
    public IPadsearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PartType = new javax.swing.JComboBox();
        Size1 = new javax.swing.JComboBox();
        searchBar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        group = new javax.swing.JComboBox();
        MClass = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        maxRow = new javax.swing.JLabel();
        rowNum = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Size2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ET1 = new javax.swing.JComboBox();
        ET2 = new javax.swing.JComboBox();
        MFG1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jLabel2.setText("Result Filters");

        jLabel1.setText("General Search:");

        PartType.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "None",
            "Connector"
            ,"Elbow, 90"
            ,"Tee, Equal"
            ,"Tube, Seamless"
            ,"Elbow, 90 Long Radius"
            ,"Cap"
            ,"Adapter"
            ,"Adapter, Male"
            ,"Adapter. Female"
            ,"Coupling"
            ,"Reducer, Concentric"
            ,"Elbow, 45"
            ,"Pipe, Welded"
            ,"Union Half"
            ,"Cross"
            ,"Lateral, 45"
            ,"Reducer, Eccentric"
            ,"Tee, Reducing"
            ,"Flange, Reducing"
            ,"Reducer, Concentric Short"
            ,"Flange, Blind"
            ,"Backing Ring"
            ,"Pipe, Seamless"
            ,"Plug, Hex"
            ,"Reducer, Bushing"
            ,"Flange, Single part"
            ,"Elbow, 22.5"
            ,"Wye"
            ,"Wye, Reducing"
            ,"Wye, Reducing Double"
            ,"Elbow, 90 Short Radius"
            ,"Flange, Van Stone"
            ,"Elbow, 30"
            ,"Elbow 11.5"
            ,"Flange, Ring"
            ,"Tee, Extended Leg"
            ,"Reducer, Concentric Machined Flush"
            ,"Elbow, 90 Extended Leg"
            ,"Bend, U"
            ,"Elbow, 45 Long Radius"
            ,"Stub End, Pipe"
            ,"Stub End, Pipe Long"
            ,"Union,  Reducing"
            ,"Bulkhead"
            ,"Union"
            ,"Gland, Long"
            ,"Gland, Short"
            ,"Union, Rotating"
            ,"Gland"
            ,"Centering Ring"
            ,"Flange, Short"
            ,"Flange, Longneck"
            ,"Flange, Bored"
            ,"Flange, Blank"
            ,"Flange, Blank Stub End"
            ,"Elbow, 60"
            ,"Wye, Double"
            ,"Elbow 15"
            ,"Strut End Cap, Red"
            ,"Cap, Allthread Rod"
            ,"Beam Clamp, Adjustable"
            ,"Double Strut Channel 10' Length"
            ,"Strut 45 Corner Angle"
            ,"Strut Channel 10' Length"
            ,"Strut L"
            ,"Strut T"
            ,"Strut U"
            ,"Strut Z"
            ,"Washer, Square"
            ,"Strut Double Wing"
            ,"Strut Splice Plate"
            ,"Strut Cross"
            ,"Strut Single Wing Left"
            ,"Strut Single Wing Right"
            ,"Double Strut Channel 20' Length"
            ,"Strut Channel 20' Length"
            ,"Bolt, Hex"
            ,"Strut Channel Nut"
            ,"Washer, Fender"
            ,"Washer, Flat"
            ,"Carbon Steel, Zinc Plated"
            ,"Washer, SAE"
            ,"Rod, Allthread 6' Length"
            ,"Rod, Allthread 10' Length"
            ,"Nut, Hex Grade 5"
            ,"Anchor, Hilti Drop-in"
            ,"Anchor, Hilti TZ"
            ,"Double Strut Post Base"
            ,"Rod Coupling"
            ,"Carbon Steel, Electrogalvanized"
            ,"Strut 90 Corner Angle"
            ,"Strut Beam Clamp (U-Bolt)"
            ,"Strut Bracket"
            ,"Strut Cap"
            ,"Strut Cush-a-Clamp"
            ,"Clamp, KF (Wingnut)"
            ,"Clamp, KF (Lever)"
            ,"Restraint Fitting"
            ,"Bellows",}));
PartType.setSelectedIndex(0);
PartType.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        PartTypeActionPerformed(evt);
    }
    });

    Size1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
        "None"
        ,"0.25\" (1/4)"
        ,"0.5\" (1/2)"
        ,"0.75\" (3/4)"
        ,"1\""
        ,"0.375\" (3/8)"
        ,"1.25\" (1 1/4)"
        ,"1.5\" (1 1/2)"
        ,"2\""
        ,"3\""
        ,"4\""
        ,"6\""
        ,"8\""
        ,"10\""
        ,"12\""
        ,"20 mm"
        ,"25 mm"
        ,"32 mm"
        ,"40 mm"
        ,"50 mm"
        ,"63 mm"
        ,"75 mm"
        ,"90 mm"
        ,"110 mm"
        ,"160 mm"
        ,"200 mm"
        ,"250 mm"
        ,"315 mm"
        ,"355 mm"
        ,"400 mm"
        ,"450 mm"
        ,"500 mm"
        ,"2.5\" (2 1/2)"
        ,"5\""
        ,"14\""
        ,"16\""
        ,"18\""
        ,"20\""
        ,"24\""
        ,"225 mm"
        ,"3.5\" (3 1/2)"
        ,"30\""
        ,"36\""
        ,"42\""
        ,"48\""
        ,"0.125\" (1/8)"
        ,"0.5\" (1/2)"
        ,"0.25\" (1/4)"
        ,"0.75\" (3/4)"
        ,"1\""
        ,"0.375\" (3/8)"
        ,"0.25\" (1/4) (Male)"
        ,"0.5\" (1/2) (Male)"
        ,"0.75\" (3/4) (Male)"
        ,"1\" (Male)"
        ,"0.25\" (1/4) (Female)"
        ,"0.5\" (1/2) (Female)"
        ,"0.75\" (3/4) (Female)"
        ,"320 mm"
        ,"4.5\" (4 1/2)"
        ,"1.625\'"
        ,"0.8125\" (13/16)\""
        ,"1.625 (1 5/8)"
        ,"4 Hole"
        ,"3 Hole"
        ,"5 Hole"
        ,"2 hole"
        ,"0.5\""
        ,"3.25\""
        ,"12\""
        ,"18\""
        ,"0.8125 (13/16)"
        ,"7 Hole"
        ,"8 Hole"
        ,"1.25\""
        ,"1.5\""
        ,"3\""}));
Size1.setSelectedIndex(0);
Size1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    Size1ActionPerformed(evt);
    }
    });

    jLabel3.setText("Group:");

    jLabel4.setText("Part Type:");

    jLabel5.setText("Material Class:");

    jLabel6.setText("Size1:");

    searchButton.setText("Search");
    searchButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchButtonActionPerformed(evt);
        }
    });

    group.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
        "None",
        "Mechanical Purchased Part",
        "Supports & Support Harware Purchased Part ",
        "Piping Hardware & Gaskets Purchased Parts",
        "Equipment, Valves, Specials, Engineered Items" }));
group.setSelectedIndex(0);
group.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    groupActionPerformed(evt);
    }
    });

    MClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
        "None", "PFA"
        ,"Polyethylene, 150 lb"
        ,"Carbon Steel, PTFE Lined 150 lb"
        ,"Polypropylene, 150 lb"
        ,"PVC Sch 40 Clear"
        ,"PVC Sch 80"
        ,"PVDF HP, PN 16"
        ,"SS 304L Sch 10"
        ,"SS 316L Sch 10"
        ,"SS 316L 10 Ra Max/EP"
        ,"SS 316L 20 Ra Max/MP"
        ,"SS 316L Coaxial 10 Ra Max/EP"
        ,"SS 316 CFOS"
        ,"SS 316L EP/UHP"
        ,"SS 316L EP"
        ,"SS 316L EP/UHP HiFlo"
        ,"SS 316L EP HiFlo"
        ,"SS 316L EP/UHP MicroFit"
        ,"SS 304"
        ,"FEP"
        ,"Carbon Steel, PTFE Lined 300 lb"
        ,"SS 304L 20 Ra Max/MP"
        ,"PVC Sch 80 Fabricated"
        ,"SS 304L"
        ,"PVDF HP, PN 16 Fabricated"
        ,"Polypropylene, 150 lb Fabricated"
        ,"Plastic"
        ,"Carbon Steel, Malleable"
        ,"Carbon Steel, Green"
        ,"Carbon Steel, Electrogalvanized"
        ,"Carbon Steel, Zinc Plated"
        ,"Washer, Square"
        ,"HDI SS 303"
        ,"Stainless Steel"
        ,"Strut 45 Corner Angle"
        ,"Carbon Steel, Zinc Plated (Dichromate Finish)"}));
MClass.setSelectedIndex(0);

jLabel7.setText("TEST");

maxRow.setText("max row:");

rowNum.setText("10");

resetButton.setText("Reset");
resetButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    resetButtonActionPerformed(evt);
    }
    });

    jLabel8.setText("Size2:");

    Size2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
        "None",
        "0.25\" (1/4)",
        "0.5\" (1/2)",
        "0.375\" (3/8)",
        "0.75\" (3/4)",
        "1\"",
        "1.25\" (1 1/4)",
        "1.5\" (1 1/2)",
        "2\"",
        "3\"",
        "4\"",
        "6\"",
        "8\"",
        "10\"",
        "12\"",
        "20 mm",
        "25 mm",
        "32 mm",
        "40 mm",
        "50 mm",
        "63 mm",
        "75 mm",
        "90 mm",
        "110 mm",
        "160 mm",
        "200 mm",
        "250 mm",
        "315 mm",
        "355 mm",
        "400 mm",
        "450 mm",
        "500 mm",
        "2.5\" (2 1/2)",
        "5\"",
        "14\"",
        "16\"",
        "18\"",
        "20\"",
        "24\"",
        "0.125\" (1/8)",
        "6 mm",
        "10 mm",
        "225 mm",
        "3.5\" (3 1/2)",
        "30\"",
        "36\"",
        "42\"",
        "48\"",
        "0.375\" (3/8)",
        "0.25\" (1/4) ",
        "0.5\" (1/2)",
        "0.75\" (3/4) ",
        "1\"",
        "0.25\" (1/4) (Male)",
        "0.5\" (1/2) (Male)",
        "0.375\" (3/8) (Male)",
        "0.75\" (3/4) (Male)",
        "1\" (Male)",
        "0.25\" (1/4) (Female)",
        "0.5\" (1/2) (Female)",
        "0.375\" (3/8) (Female)",
        "0.75\" (3/4) (Female)",
        "0.125\" (1/8)",
        "320 mm",
        "4.5\" (4 1/2)",
        "3.25\"",
        "0.8125\" (13/16)",
        "1.625 (1 5/8)",
        "5 Hole",
        "3 Hole",
        "4 Hole",
        "13/16\"",
        "1 5/8\"",
        "2 Hole",
        "1.25\"",
        "0.5\"",
        "3.75\"",
        "5.5\"",
        "3.25\"",
        "12\"",
        "18\"",
        "0.8125 (13/16)",
        "7 Hole",
        "8 Hole",
        "1.25\"",
        "1.5\"",
        "3\""
    }));

    jLabel9.setText("Manufacturer 1:");

    jLabel12.setText("End Type 2:");

    jLabel13.setText("End Type 1:");

    ET1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
        "None",
        "MPT",
        "Flare",
        "Socket Fusion",
        "Butt Fusion",
        "Spigot",
        "Socketweld",
        "Flanged, Raised Face",
        "Flanged, Flat Face",
        "Socket Cement",
        "FPT",
        "FPT, SS Reinforced",
        "Grooved",
        "Buttweld",
        "Autoweld",
        "Compression",
        "VCR Male",
        "VCR",
        "VCR Female",
        "Tube Butt Weld",
        "Flange, MF",
        "Flange, KF"
    }));
    ET1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ET1ActionPerformed(evt);
        }
    });

    ET2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
        "None",
        "Flare",
        "MPT",
        "Socket Fusion",
        "FPT",
        "Butt Fusion",
        "Socketweld",
        "Flanged, Raised Face",
        "Flanged, Flat Face",
        "Socket Cement",
        "FPT, SS Reinforced",
        "FPT, Special Reinforced Encapsulated",
        "FPT, Brass Insert",
        "Buttweld",
        "Lapjoint",
        "Autoweld",
        "Compression",
        "VCR Male ",
        "Tube",
        "FPT",
        "MPT",
        "Tube Butt Weld",
        "VCR Female",
        "VCR",
        "Flange, MF",
        "Flange, KF"}));

MFG1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
"None",
"George Fischer",
"Charlotte",
"Allied EG",
"Asahi",
"Valex",
"Cardinal UHP",
"Swagelok"}));
MFG1.setSelectedIndex(0
    );

    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainPanelLayout.createSequentialGroup()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(searchButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(resetButton))
                        .addComponent(PartType, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MClass, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addComponent(Size1, 0, 100, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Size2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ET1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MFG1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(group, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ET2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(searchBar)))
            .addContainerGap())
        .addGroup(mainPanelLayout.createSequentialGroup()
            .addGap(55, 55, 55)
            .addComponent(maxRow)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(rowNum, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(145, 145, 145))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(134, 134, 134))))
    );
    mainPanelLayout.setVerticalGroup(
        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(PartType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(MClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Size1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(Size2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13)
                .addComponent(ET1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ET2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel12))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel9)
                .addComponent(MFG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchButton)
                .addComponent(resetButton))
            .addGap(26, 26, 26)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rowNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(maxRow))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        searchBar.setText("");
        group.setSelectedIndex(0);
        PartType.setSelectedIndex(0);
        MClass.setSelectedIndex(0);
        Size1.setSelectedIndex(0);
        Size2.setSelectedIndex(0);
        ET1.setSelectedIndex(0);
        ET2.setSelectedIndex(0);
        MFG1.setSelectedIndex(0);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        gatherList();
        if(isFirstTime){
            try {
                j = new solrj(resultPanel);
            }
            catch (SolrServerException ex) {
                Logger.getLogger(IPadsearch.class.getName()).log(Level.SEVERE, null, ex);
            }
            isFirstTime =false;
        }
        j.setRowNum(rowNum.getText());
        resultPanel.getTextField().setText(searchBar.getText());
        repaint();
        try {
            j.executeQuery(queryList);
        }
        catch (SolrServerException | IOException ex) {
            Logger.getLogger(IPadsearch.class.getName()).log(Level.SEVERE, null, ex);
        }
        resultPanel.switchToResultPanel(this);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void Size1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Size1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Size1ActionPerformed

    private void PartTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartTypeActionPerformed

    private void ET1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ET1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ET1ActionPerformed
    
    // Gather all the texts from the search bar and drop down.
    private void gatherList(){
        queryList[0] = searchBar.getText();
        if(group.getSelectedIndex() != 0){
            resultPanel.setfilterText(group.getSelectedItem().toString());
            queryList[1] = "\"" + group.getSelectedItem().toString() + "\"";
        }
        else{
            queryList[1] = "";
        }
        if(PartType.getSelectedIndex() != 0){
            resultPanel.setfilterText(PartType.getSelectedItem().toString());
            queryList[2] = "\"" + PartType.getSelectedItem().toString()+ "\"";
        }
        else{
            queryList[2] = "";
        }
        if(MClass.getSelectedIndex() != 0){
            resultPanel.setfilterText(MClass.getSelectedItem().toString());
            queryList[3] = "\"" + MClass.getSelectedItem().toString() + "\"";
        }
        else{
            queryList[3] = "";
        }
        if(Size1.getSelectedIndex() != 0){
            resultPanel.setfilterText(Size1.getSelectedItem().toString());
            String inch = insertBackSlash(Size1.getSelectedItem().toString());
            queryList[4] = inch;
        }
        else{
            queryList[4] = "";
        }
        if(Size2.getSelectedIndex() != 0){
            resultPanel.setfilterText(Size2.getSelectedItem().toString());
            String inch = insertBackSlash(Size2.getSelectedItem().toString());
            queryList[5] = inch;
        }
        else{
            queryList[5] = "";
        }
        if(ET1.getSelectedIndex() != 0){
            resultPanel.setfilterText(ET1.getSelectedItem().toString());
            queryList[6] = "\"" + ET1.getSelectedItem().toString() + "\"";
        }
        else{
            queryList[6] = "";
        }
        if(ET2.getSelectedIndex() != 0){
            resultPanel.setfilterText(ET2.getSelectedItem().toString());
            queryList[7] = "\"" + ET2.getSelectedItem().toString() + "\"";
        }
        else{
            queryList[7] = "";
        }
        if(MFG1.getSelectedIndex() != 0){
            resultPanel.setfilterText(MFG1.getSelectedItem().toString());
            queryList[8] = MFG1.getSelectedItem().toString();
        }
        else{
            queryList[8] = "";
        }
    }
    public void switchToSearchPanel(){
        setContentPane(mainPanel);
        repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPadsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPadsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPadsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPadsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IPadsearch().setVisible(true);
            }
        });
    }
    
    // insert backslash before quotations.
    public String insertBackSlash(String tokenIndex){
        String newstr = "";
        if(tokenIndex.charAt(tokenIndex.length() - 1) == '\"'){
            newstr = tokenIndex.substring(0, tokenIndex.length() - 1) + "\\\"";
        }
        else
            for(int i = 0; i < tokenIndex.length(); i++){
                if(tokenIndex.charAt(i) == '"')
                    newstr += "\\\"";
                else
                    newstr += tokenIndex.charAt(i);
            }
        return newstr;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ET1;
    private javax.swing.JComboBox ET2;
    private javax.swing.JComboBox MClass;
    private javax.swing.JComboBox MFG1;
    private javax.swing.JComboBox PartType;
    private javax.swing.JComboBox Size1;
    private javax.swing.JComboBox Size2;
    private javax.swing.JComboBox group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel maxRow;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField rowNum;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
